#!/usr/bin/env node
/* ============================================================================
 * Build dist/oyako-hotel.html — the whole site in one file you can email.
 *
 * Inlines styles.css, site.config.js, app.js, every bundled font and every
 * photograph as data URIs, so the result opens by double-click with no folder
 * beside it and no network connection.
 *
 * Node built-ins only, no dependencies.
 *
 *   node export-single.mjs [--out dist/oyako-hotel.html] [--quiet]
 * ==========================================================================*/
import { readFileSync, writeFileSync, mkdirSync, statSync, readdirSync } from 'node:fs';
import { join, dirname, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const QUIET = process.argv.includes('--quiet');
const outIdx = process.argv.indexOf('--out');
const OUT = join(ROOT, outIdx === -1 ? 'dist/oyako-hotel.html' : process.argv[outIdx + 1]);

const MIME = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.woff2': 'font/woff2',
  '.woff': 'font/woff',
};

const read = (p) => readFileSync(join(ROOT, p), 'utf8');
const dataUri = (p) => {
  const ext = extname(p).toLowerCase();
  const mime = MIME[ext];
  if (!mime) throw new Error(`no MIME type for ${p}`);
  return `data:${mime};base64,${readFileSync(join(ROOT, p)).toString('base64')}`;
};

/* 1. Work out every local asset referenced by the page, its stylesheet or its
 *    settings file. The config names images as plain strings, and app.js copies
 *    those strings into markup at runtime, so a static HTML-only scan is not
 *    enough: the settings file has to be scanned too. */
const sources = {
  html: read('index.html'),
  css: read('styles.css'),
  config: read('site.config.js'),
  app: read('app.js'),
};
const blob = Object.values(sources).join('\n');

const assets = [...new Set(
  (blob.match(/assets\/(?:img|fonts)\/[A-Za-z0-9._-]+\.[A-Za-z0-9]+/g) || []),
)].sort();

const missing = assets.filter((p) => {
  try { statSync(join(ROOT, p)); return false; } catch { return true; }
});
if (missing.length) {
  console.error('referenced assets that do not exist:\n  ' + missing.join('\n  '));
  process.exit(1);
}

/* 2. Inline the three files into the document. */
let html = sources.html;
const before = html.length;

html = html.replace(
  /<link rel="stylesheet" href="styles\.css">/,
  () => `<style>\n${sources.css.trim()}\n</style>`,
);
if (html.length === before) throw new Error('could not inline styles.css');

for (const [file, code] of [['site.config.js', sources.config], ['app.js', sources.app]]) {
  const tag = `<script src="${file}"></script>`;
  if (!html.includes(tag)) throw new Error(`could not inline ${file}`);
  // a literal </script> inside the code would close the tag early
  const safe = code.replace(/<\/script>/gi, '<\\/script>');
  // replace with a function: a plain string replacement would expand `$'` (which
  // app.js contains, in its currency formatter) into the rest of the document
  html = html.replace(tag, () => `<script>\n${safe.trim()}\n</script>`);
}

/* 3. Swap every asset path for a data URI. This happens after the code is
 *    inlined, so it fixes runtime-generated <img src> as well as static ones. */
let inlined = 0;
let inlinedBytes = 0;
for (const asset of assets) {
  const uri = dataUri(asset);
  const parts = html.split(asset);
  if (parts.length > 1) inlined++;
  html = parts.join(uri);
  inlinedBytes += statSync(join(ROOT, asset)).size;
}

/* 4. Anything still pointing at a local file would break in a single file.
 *    Only real paths count: the inlined scripts contain markup templates like
 *    src="' + esc(x) + '", which must not be mistaken for a reference. */
const leftovers = [...new Set(
  (html.match(/(?:src|href)="[^">'+]+\.(?:jpg|jpeg|png|webp|svg|woff2?|css|js)"/g) || []),
)];
if (leftovers.length) {
  console.error('still references local files after inlining:\n  ' + leftovers.join('\n  '));
  process.exit(1);
}

html = html.replace(
  '<head>',
  () => '<head>\n<!-- Generated by export-single.mjs — do not edit. ' +
    'The editable site is index.html + site.config.js + app.js + styles.css. -->' +
    // Every photograph is already inline here as a data URI, so a srcset of
    // separate files would be pointless (and would double the file). app.js
    // reads this flag and skips the responsive-image attributes.
    '\n<script>window.OYAKO_INLINED = true;</script>',
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, html);

if (!QUIET) {
  const size = statSync(OUT).size;
  const fonts = readdirSync(join(ROOT, 'assets/fonts')).filter((f) => f.endsWith('.woff2')).length;
  console.log(
    `${relative(ROOT, OUT)}  ${(size / 1024 / 1024).toFixed(2)} MB\n` +
    `  inlined ${inlined} assets (${(inlinedBytes / 1024 / 1024).toFixed(2)} MB of ` +
    `images and fonts), ${fonts} font files on disk\n` +
    `  no external references remain`,
  );
}
